### ISSUE TITLE
Not working with the newest jQuery UI version

### ISSUE THREAD

**Issue by Johnny99211** [RWAP/jquery-ui-touch-punch#2]
Since some versions touchpunch don't works anymore. Can you might check that out and post a fix on your fork?

**Comment by RWAP** [comment]
Unfortunately, none of my sites use jQuery v2 because of other incompatabilities....

**Comment by Johnny99211** [comment]
Oh okay, I've had the hope that it's just a small fix. I'm using it within WordPress and WordPress unses version 1.18.x by default and this version also don't works which is really sad.

**Comment by RWAP** [comment]
I assume you mean jQuery v1.8 (it is now v3.4.1 !), but which version of jQuery UI - What errors do you get in the console if anything?  

Does it connect but simply not produce the expected results on a mobile device?  If so, then which mobile device - as Apple and Android devices produce different events unfortunately - and remote debugging of an Apple phone seems to need an Apple Mac !!

The problem is that jQuery has been completely re-written which causes issues with all sorts of things - there used to be a compatability module, but I could not see that in the current sources.

Even the jQuery-Mobile has not been updated in 3 years and fails to cover all of the devices supported by touch-punch.

In reality - this needs someone who has a lot of knowledge about jQuery-UI as well as people with the right equipment to debug Android, Apple and even Microsoft touch devices...

**Comment by Johnny99211** [comment]
I've following versions installed:

jQuery: 1.12.4
jQuery UI: 1.11.4
touchpunch: 0.2.2

With this constellation, touch don't works. If I downgrade jQuery UI to 1.8.12, the touch events are working but I can't sort my elements. So with other words I can move the elements but when I want to place the element to a new position, the element goes back to his old position.

Edit:
I've also tried to newest jQuery UI and the latest touchpunch but I had the same issue with that.

**Comment by RWAP** [comment]
Have you tried the v1.0.0 touchpunch from this particular fork (not the original)?

We have sortable working on our website using jQuery 1.11.3, and jQuery 1.11.4 - so it suggests it might be something else causing this issue

**Comment by Johnny99211** [comment]
Yes, I've tried your version too. And a few minutes ago I've tried it again - no reaction. I'll hide now the handles on any touch devices so that my customers can only sort the elements on non-touch devices. Currently the only solution I have.

**Comment by RWAP** [comment]
@Johnny99211  Have you tried the latest version of this branch to see if it now fixes your issue?

**Comment by melloware** [comment]
I just tested with Jquery 3.4.1 and Jquery UI 1.12.1 and this patch is working great.  I simply changed "bind/unbind" to "on/off" in two lines of code.   I would say this ticket is safe to close.
