### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by hn1** [RWAP/jquery-ui-touch-punch#29]
What is this script supposed to do as it seems to do NOTHING!

**Comment by melloware** [comment]
Works fine for me...

**Comment by hn1** [comment]
Apart from including the jquery UI and making the element draggable() is there anything else one is supposed to do?
Thanks.

**Comment by RWAP** [comment]
The script is designed to ensure that mouse coontrols in jQuery UI work on a mobile phone.  It works so far as I am aware - draggable is probably one of the most awkward things to implement as it all depends on getting the DOM in the correct order to ensure that a row is draggable, rather than just an element (for example).

Detecting it on a mobile phone is then problematic, as it depends on what guesture you are going to use to try dragging something !!

**Comment by hn1** [comment]
This library does NOT work. Please withdraw as people try and see where they are going wrong and waste their time while in actual fact it just DOES NOT WORK.

**Comment by melloware** [comment]
@hn1 works fine for me in many large projects...  Not sure what you issue is...

**Comment by hn1** [comment]
My issue is that it does not work and you are wasting people's time. And several people we are working with also confirmed that your solution does not work. That is my issue! Please remove this rubbish so that people do not waste theor time. Thanks!

**Comment by melloware** [comment]
Weird. You must be doing something wrong. This project isn't wasting my time 😀

**Comment by melloware** [comment]
@bazineta does it work for you?
