### ISSUE TITLE
Not working with Windows Touch devices

### ISSUE THREAD

**Issue by justinx99** [RWAP/jquery-ui-touch-punch#7]
Hello, TouchPunch is not working with different touch devices. (Firefox 68.0.2 64bit). It works fine on Android and IOS devices, even with a Surface, but its not with Windows Laptops (Schenker and Lenovo) with Touch.

**Comment by melloware** [comment]
So to be clear the scenario that is not working is FireFox Browser + Lenovo touchscreen laptop?

**Comment by RWAP** [comment]
The Firefox browser and touch device emulation is very hit and miss for a lot of things unfortunately.  This would need testing on a proper Lenova touchscreen laptop to be certain.

**Comment by melloware** [comment]
@RWAP I actually have a Lenovo touchscreen laptop so let me do some investigating.

**Comment by RWAP** [comment]
One thing which might be better is to change the line:

`  $.support.touch = ('ontouchstart' in document || 'ontouchstart' in window || navigator.maxTouchPoints > 0 || navigator.msMaxTouchPoints > 0);`

to read:


`  $.support.touch = ('ontouchstart' in document || 'ontouchstart' in window || window.DocumentTouch && document instanceof window.DocumentTouch || navigator.maxTouchPoints > 0 || navigator.msMaxTouchPoints > 0);`

**Comment by melloware** [comment]
Using the Modernizr code which is very well tested.
https://github.com/Modernizr/Modernizr/blob/377a6303b3b6d400979eeae351e1dcf43972eef4/feature-detects/touchevents.js#L40

This fixes it by adding both DocumentTouch and TouchEvent

```javascript
$.support.touch = ( 'ontouchstart' in document 
   || 'ontouchstart' in window 
   || window.TouchEvent 
   || (window.DocumentTouch && document instanceof DocumentTouch) 
   || navigator.maxTouchPoints > 0 
   || navigator.msMaxTouchPoints > 0
);
```

Chrome also changed its behaviour since v70 and recommends the TouchEvent object for detection: https://www.chromestatus.com/feature/4764225348042752

**Comment by justinx99** [comment]
So, i tryed more devices. It seems devices independet, it works only in the Chrome Browser, not with Firefox or Edge. 
I tested it on 3 Touch devices with newest Firefox. Huawai Matebook X Pro, Schneker Laptop, Lenovo IdeaCentre AIO 910. All got same results. Only Chrome working! 
Also i changed the code to you advice, but i got same results.

I fixed that issues in Firefox with changing

` if (!$.support.touch || !$.ui.mouse) {
        false;
    }`

to:

`  if (!$.support.touch || !$.ui.mouse) {
        true;
    }`

it might not be the best solution, but for now it works.

**Comment by RWAP** [comment]
Yes - changing those lines if (!$.support.touch || !$.ui.mouse) { true; } is dangerous for other devices because it allows the code to work even if the browser does not support touch or mouse support.  

Please try the updated version which should enable Firefox to get past the !$.support.touch statement.

**Comment by justinx99** [comment]
I am using Firefox 68.0.2, which is the newest version.

**Comment by justinx99** [comment]
Yes - your updated version works on my touch devices, running the newest firefox version. Thank you for the awesome update! 😊👌

**Comment by RWAP** [comment]
Excellent - we can close this issue now - many thanks for testing and @melloware for spotting the change required
